### ISSUE TITLE
Help needed in a large-scale LP problem: always ITERATION_LIMIT 

### ISSUE THREAD

**Issue by ShuhuaGao** [ds4dm/Tulip.jl#58]
I am dealing with an LP problem involved in superconductor magnet design. It is essentially an L1-norm minimization problem, which is transformed into an LP. The design variables are collected in vector $I_L$, and auxiliary variables $t >= |I_L|$ (element-wise) are introduced. The form of the final LP is shown below.
![Snipaste_2020-09-16_20-35-23](https://user-images.githubusercontent.com/20141984/93337784-31899000-f85c-11ea-9aa8-f1ccd3e8d05b.png)
I tried to solve this problem with JuMP and Tulip. The LP problem is a little high dimensional with the following info generated by Tulip:
```
Problem info
  Name        :
  Constraints : 11000
  Variables   : 5000
  Non-zeros   : 2509954

Reduced problem info
  Constraints : 5996  (removed 5004)
  Variables   : 5000  (removed 0)
  Non-zeros   : 2500000  (removed 9954)
Presolve time : 0.042s

Optimizer info
Linear solver options
  Arithmetic   : Float64
  Backend      : CHOLMOD
  System       : Augmented system
```
I have access to MATLAB and [Gurobi ](https://github.com/jump-dev/Gurobi.jl) and thus first tested them (both with default settings). The result is summarized below:
- MATLAB: SUCCESS with optimal objective value 474048.424 in about 20 seconds.
- Gurobi: SUCCESS with the same optimal objective value in about 6 seconds.

Next, I tried Tulip. With the default parameters, there was always *Solver exited with status Trm_IterationLimit*. I thus increased the `BarrierIterationsLimit` parameter by `set_optimizer_attribute(model, "BarrierIterationsLimit", 500)`, though I don't know whether it is the proper fix. After a very very long time (around one hour), I got the following result in Tulip (the last two lines are added in my code):
```
 499  +4.7330511e+05  +4.7330511e+05  8.87e-10 1.91e-11 2.33e-10  1.4e-18  3453.77
 500  +4.7330527e+05  +4.7330527e+05  1.97e-09 4.85e-11 1.97e-11  2.1e-14  3460.47
Solver exited with status Trm_IterationLimit
- Termination status: ITERATION_LIMIT
- Obj value: NaN
```
I have even tested Tulip for 5000 iterations but still got the same result.

I have a few questions:
1. Can Tulip handle problems of such a scale?
2. If it can, how should I set the parameters to get a _reasonable_ result in reasonable running time? 
3. Or is there any improvement I should make in problem formulation? I am mostly a user of optimization solvers and lack professional knowledge in this field.

Any suggestions are appreciated.

[**Code for reproduction**] (The Julia file is also available in [Google Drive lp_tulip.jl](https://drive.google.com/file/d/195qkWr3bYwxc7S-TB15VrHXRzHn81hWO/view?usp=sharing))
```julia
using JuMP, Tulip
import LinearAlgebra
using JLD2

@load "lp_data.jld2" Imax D̄z F̄r F̄z B0 ϵ Brf Bzf aL

n = size(D̄z, 2)  # length of the design vector IL
model = Model(Tulip.Optimizer)
set_optimizer_attribute(model, "BarrierIterationsLimit", 500)
set_optimizer_attribute(model, "OutputLevel", 2)
@variable(model, I[1:n])
@variable(model, t[1:n]);
@constraints(model, begin
        I .<= t
        I .>= -t
        I .<= Imax
        I .>= -Imax
        D̄z*I .<= B0 * (1 + ϵ)
        D̄z*I .>= B0 * (1 - ϵ)
        F̄r*I .<= Brf
        F̄r*I .>= -Brf
        F̄z*I .<= Bzf
        F̄z*I .>= -Bzf
        end)
@objective(model, Min, LinearAlgebra.dot(aL, t))
optimize!(model)
st = termination_status(model)
println("- Termination status: ", st)
println("- Obj value: ", objective_value(model))
```

[**Data: lp_data.jld2**]
Please download from [Google Drive lp_data.jld2](https://drive.google.com/file/d/18q2ri9lVfP27l3rigbS9P1QTudn_P1Fa/view?usp=sharing).
 
[System info]
```
julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, ivybridge)
```
and Tulip v0.6.0

(The Gurobi output is also listed below for your information)
```
Academic license - for non-commercial use only
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
Gurobi Optimizer version 9.0.2 build v9.0.2rc0 (win64)
Optimize a model with 11000 rows, 5000 columns and 2504998 nonzeros
Model fingerprint: 0x682571a4
Coefficient statistics:
  Matrix range     [1e-13, 1e+00]
  Objective range  [2e-01, 4e-01]
  Bounds range     [0e+00, 0e+00]
  RHS range        [3e-04, 5e+03]

Concurrent LP optimizer: dual simplex and barrier
Showing barrier log only...

Presolve removed 2500 rows and 2504 columns
Presolve time: 1.91s
Presolved: 2500 rows, 8496 columns, 2497498 nonzeros

Ordering time: 0.05s

Barrier statistics:
 AA' NZ     : 3.124e+06
 Factor NZ  : 3.126e+06 (roughly 30 MBytes of memory)
 Factor Ops : 5.211e+09 (less than 1 second per iteration)
 Threads    : 3

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -9.11884571e+06  9.98372088e+07  1.00e-01 6.11e+03  2.32e+04     3s
   1  -5.96551043e+06  1.95735779e+07  4.08e-04 5.15e+03  2.57e+03     4s
   2  -1.19952925e+06  3.12413253e+06  1.35e-06 6.82e+02  4.03e+02     4s
   3   4.36598159e+04  1.92207121e+06  1.11e-07 4.10e+02  1.74e+02     5s
   4   2.47263228e+05  1.01981004e+06  4.09e-08 1.65e+02  7.21e+01     5s
   5   3.27506348e+05  8.65928047e+05  2.16e-08 1.23e+02  5.06e+01     6s

Barrier performed 5 iterations in 5.74 seconds
Barrier solve interrupted - model solved by another algorithm


Solved with dual simplex
Solved in 2001 iterations and 5.76 seconds
Optimal objective  4.740484236e+05
- Termination status: OPTIMAL
- Obj value: 474048.42359098565
```

**Comment by mtanneau** [comment]
Thanks for sharing this.

### Numerics
High iteration count is generally a sign of bad numerics.
I also tried solving the model with Gurobi's barrier only, and it switched to crossover after 110 iterations
  ```
                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
...
 108   4.73402517e+05  4.71854909e+05  2.41e-03 2.48e-01  7.48e-02    67s
 109   4.73381272e+05  4.71852992e+05  2.39e-03 2.48e-01  7.49e-02    68s
 110   4.73995393e+05  4.71862104e+05  2.30e-03 2.47e-01  7.45e-02    68s

Barrier performed 110 iterations in 68.17 seconds
Sub-optimal termination - objective 4.55040426e+05
  ```
(notice the not-so-small primal and dual infeasibilities).
So, regardless of which solver you end up using, numerics are definitely not great here.

I noticed that your data (namely, `D̄z`, `F̄r`, `F̄z`, `B0`, `ϵ`, `Brf`, `Bzf`) has a lot of very small coefficients, typically between `1e-8` and `1e-5`, and as small as `1e-24`. The latter get dropped by Gurobi as indicated at the beginning of its log:
```
Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored
```
  You can check the Gurobi guidelines for numerical issues [here](https://www.gurobi.com/documentation/9.0/refman/num_grb_guidelines_for_num.html#sec:Numerics).


### Performance
There's no intrinsic limit to the size of models that Tulip can solve: the limiting factors are memory and how long you're willing to wait.

This model is not that big (10k constraints and 5k variables), but it does have a lot of non-zero coefficients, mainly because  `D̄z`, `F̄r`, `F̄z` are dense matrices.
It would be cheaper to introduce additional variables, for instance replacing
```
F̄z*I .<= Bzf
F̄z*I .>= -Bzf
```
with
```julia
@variable(model, -Bzf <= z[1:size(F̄z, 1)] <= Bzf)
z .== F̄z*I
```
This approach can be applied to constraints (14.d)-(14.f).
Additionally, constraints (14.c) can be replace by bounds on the `I` variables:
```
@variable(model, -Imax <= I[1:n] <= Imax)
```

Doing so removes make the model about 50% smaller (in terms of non-zeros) and, on my machine, Tulip now takes ~0.5s / iteration (vs ~8s before). It also makes Gurobi ~3x faster per iteration.

I could not quite get around the numerical issues just yet. The only thing that did work was to use `Double64` arithmetic, but that slows down everything and you cannot do it from JuMP.

**Comment by ShuhuaGao** [comment]
Thank you very much for your help. Regarding the numerical issues, the small numbers may be caused by the unit used (Tesla for the magnetic field). Will it help if I multiply both sides by a proper number? That is equivalent to switching to a smaller unit (like Gauss = 10^(-4) Telsa). 

I am a little confused by your suggestion on bound constraints. For example, `@variable(model, -Imax <= I[1:n] <= Imax)` is mathematically equivalent to 
```
I .<= Imax
I .>= -Imax
```
Does it make any difference to JuMP or Tulip? Does the latter lead to more constraints? I thought that JuMP would transform them into a uniform form internally.  Anyway, I will play with them and give more feedback soon.

**Comment by ShuhuaGao** [comment]
***Model transformation***

According to the above advice, I have changed the model in JuMP as follows.
```julia
n = size(D̄z, 2)  # length of IL
model = Model(Gurobi.Optimizer)
@variable(model, -Imax <= I[1:n] <= Imax)
@variable(model, t[1:n]);
@variable(model, B0 * (1 - ϵ) <= x[1:size(D̄z, 1)] <= B0 * (1 + ϵ))
@variable(model, -Brf <= y[1:size(F̄r, 1)] <= Brf)
@variable(model, -Bzf <= z[1:size(F̄z, 1)] <= Bzf)

@constraints(model, begin
        I .<= t
        I .>= -t
        x .== D̄z*I
        y .== F̄r*I
        z .== F̄z*I
        end)
```
In Gurobi, the new result is
```
...
Solved with dual simplex
Solved in 1968 iterations and 4.76 seconds
Optimal objective  4.740198196e+05
- Termination status: OPTIMAL
- Obj value: 474019.8196242394
```
It is indeed one second faster 👍 . However, the optimal value changed slightly from 474048 to 474019. I guess it may be caused by some numerical issues.  

Then I changed the solver to Tulip (with default settings, at most 100 iterations).  The problem info is that 
```
Problem info
  Name        : 
  Constraints : 5500
  Variables   : 5500
  Non-zeros   : 1257977

Reduced problem info
  Constraints : 5498  (removed 2)
  Variables   : 5498  (removed 2)
  Non-zeros   : 1255498  (removed 2479)
Presolve time : 0.037s
```
As we see, the number of constraints is greatly reduced, which I do not understand here. It seems that the bound constraints in, e.g., `@variable(model, -Imax <= I[1:n] <= Imax)`, are not counted, but only the `@constraints` part is counted. Why? Does it mean that, if I put the bound constraints in `@constraints` section, JuMP cannot recognize it? Is the bound constraint handled specially in LP? 

The running time of Tulip on my PC is about 2s/iteration. Nevertheless, the result is still  
```
Solver exited with status Trm_IterationLimit
- Termination status: ITERATION_LIMIT
- Obj value: NaN
```
Next, I will try to deal with the possible numerical issues.

**Comment by ShuhuaGao** [comment]
**_Numerical issues_**

As mentioned above, I applied a simple trick: multiply each side of the constraints (14d)-(14f) by a factor `m`. I chose `m=10^4` here, which amounts to changing the unit from Telsa to Gauss for magnetic fields. That is, insert the following code snippet before model construction,
```julia
@load "lp_data.jld2" Imax D̄z F̄r F̄z B0 ϵ Brf Bzf aL
m = 1e4
D̄z .*= m
F̄r .*= m
F̄z .*= m
B0 *= m
Brf *= m
Bzf *= m
```
It worked like a magic 💯. Now Tulip took less than 50 iterations (around 103 s) to get the optimal result.
```
...
  45  +4.7404842e+05  +4.7404842e+05  4.32e-13 5.80e-10 1.18e-09  5.8e-28  95.94
  46  +4.7404842e+05  +4.7404842e+05  4.75e-14 1.65e-05 7.61e-09  2.9e-31  98.00
  47  +4.7404842e+05  +4.7404842e+05  3.58e-14 8.27e-09 5.03e-09  1.4e-34  100.96
  48  +4.7404842e+05  +4.7404842e+05  2.79e-14 4.14e-12 4.43e-09  7.2e-38  103.17
Solver exited with status Trm_Optimal
- Termination status: OPTIMAL
- Obj value: 474048.42363418965
```
Gurobi got the same optimal value with the same `m` in about 3.78 s.

I also tested another two different values of `m` (max iteration is 100).

1. `m=1e3`
```
...
  99  +4.7395035e+05  +4.7395035e+05  1.22e-08 1.95e-06 1.10e-08  1.0e-14  227.81
 100  +4.7395228e+05  +4.7395228e+05  1.22e-08 2.37e-05 1.80e-08  1.4e-15  230.36
Solver exited with status Trm_IterationLimit
- Termination status: ITERATION_LIMIT
- Obj value: 473952.2800541247
```
Though the status is iteration limit reached, the final value is very close to the optimal one. 

- [ ] My question is, why for some cases with  *ITERATION_LIMIT* we get a valid objective value and for others we only get NaN?

2. `m=1e5`
A result similar to `m=1e4` is obtained. 
```
  40  +4.7404842e+05  +4.7404842e+05  6.73e-14 4.11e-12 1.99e-09  1.5e-66  86.79
  41  +4.7404842e+05  +4.7404842e+05  9.25e-14 1.46e-12 1.69e-09  7.3e-70  88.91
Solver exited with status Trm_Optimal
- Termination status: OPTIMAL
- Obj value: 474048.4235496756
```
It seems thus that `m>=1e4` is enough.

Final thoughts:
1. Very small numeric values are not welcome in LP (or any optimization problems), right?
2. If so, I am wondering why Gurobi (as well as MATLAB) can handle the numeric issues automatically but Tulip cannot. Perhaps a preprocessing step may be injected into Tulip to spot and handle common numeric pitfalls, though I have no clear idea.

**Comment by mtanneau** [comment]
Regarding your previous comments:

> I am a little confused by your suggestion on bound constraints.

In simplex and interior-point solvers, bound constraints typically come "for free", i.e., they do not introduce additional non-zero coefficients and are handled more efficiently than general constraints. It is indeed mathematically equivalent, it just tends to be faster.
What typically happens at presolve is that constraints of the form `I <= Imax` will be replaced by the corresponding bounds on `I`. This is done by the solvers, not by JuMP.

> As we see, the number of constraints is greatly reduced, which I do not understand here.

The number of constraints is divided by 2 because the `2m` inequalities `D̄z*I .<= B0 * (1 + ϵ)`, `D̄z*I .>= B0 * (1 - ϵ)` are replaced with the `m` equalities `x .== D̄z*I`. Variable bounds do not count against the number of rows of the constraint matrix.
Finally, since factorizing a matrix of size `n` takes roughly `O(n^3)` time, dividing the size by two gives an ~8x speedup on the factorization, which is the most time consuming. These are only rough estimates, obviously.

> why for some cases with ITERATION_LIMIT we get a valid objective value and for others we only get NaN?

At each iteration, Tulip checks for primal and dual feasibility of the current iterate.
It may be that the solver hit the iteration limit, but that a primal feasible solution is available, in which case its objective value will be reported.
You can check whether this is the case by calling `primal_status(model)` and `dual_status(model)`.

> Very small numeric values are not welcome in LP (or any optimization problems), right?

As a rule of thumb, no. Ideally, all your input coefficients would roughly be between `1e-4` and `1e4`. Once again , the [Gurobi documentation](https://www.gurobi.com/documentation/9.0/refman/num_grb_guidelines_for_num.html#sec:Numerics) has a lot of information on this.
There are many (combined) ways of addressing numerical issues, from presolve and scaling to more robust linear algebra. Tulip is not yet as advanced as others on this point, but hopefully will eventually catch up 🤞

**Comment by ShuhuaGao** [comment]
Thank you for all the responses. I indeed learned a lot, especially about the bound constraints.  It makes sense and no wonder that MATLAB [linprog](https://www.mathworks.com/help/optim/ug/linprog.html) has a form `x = linprog(f,A,b,Aeq,beq,lb,ub)` (i.e., list bound constraints separately).  I will check the Gurobi documentation on numerical issues later.

It seems that I should read Boyd's Convex Optimization carefully again to learn about the fundamental theory. 😆 Finally, thank you for this useful, though not perfect yet, package. Gurobi is good but needs a costly license 😭.
